name: Bandit Code Scan

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  bandit_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          pip install bandit

      - name: Run Bandit
        id: bandit_scan
        run: bandit -r . -f json -o bandit_output.json || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
         name: bandit-findings
         path: bandit_output.json

      - name: Analyze Bandit Results
        id: analyze_results
        run: |
          if [ -s bandit_output.json ]; then
            cat bandit_output.json
            CRITICAL_COUNT=$(jq '[.results[] | select(.issue_severity | IN("CRITICAL", "HIGH", "MEDIUM"))] | length' bandit_output.json)
            if [ "$CRITICAL_COUNT" -gt 0 ]; then
              echo "block=true" >> $GITHUB_ENV
            else
              echo "block=false" >> $GITHUB_ENV
            fi
          else
            echo "block=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Add PR Comment and Block/Merge
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}

          if [ "$block" == "true" ]; then
            # Add Block Comment
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
              -d '{"body": "Block"}'
            exit 1
          else
            # Add Successful Comment
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
              -d '{"body": "Successful"}'

            # Merge Pull Request
            curl -X PUT \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/merge \
              -d '{"merge_method": "merge"}'
          fi
